README.md
assets/ui/FuzzPanelMain.css
assets/ui/FuzzPanelMain.js
package.json
src/fuzzer/Fuzzer.ts
src/fuzzer/adapters/JestAdapter.ts
src/fuzzer/analysis/typescript/FunctionDef.test.ts
src/fuzzer/analysis/typescript/FunctionDef.ts
src/fuzzer/generators/GeneratorFactory.test.ts
src/ui/FuzzPanel.ts
yarn.lock

In addition to exporting a test suite in Jest format, this PR also disables the CodeLens for non-exported functions, skips duplicate inputs during a test run, and improves the results grid readability.

feat: save tests and export to Jest

---

assets/ui/FuzzPanelMain.css
assets/ui/FuzzPanelMain.js
package.json
src/fuzzer/Fuzzer.ts

This PR also adds a maximum duplicate counter to the main fuzzing loop to improve the speed at which the fuzzer returns results when it has likely exhausted the input range.

fix: make pin button easier to find

---

package.json
src/telemetry/Logger.ts
src/telemetry/Telemetry.ts
tsconfig.json
yarn.lock

Fixed an issue where telemetry would log in some cases when telemetry was de-activated. 
This PR also removes the restart requirement to turn telemetry on and off.

fix: telemetry de-activation

---

README.md
package.json

We moved the repo to the NaNofuzz org. Update the repo link in package.json and add the paper pre-print to the readme.

chore: update repo link & add paper preprint

---

src/ui/FuzzPanel.ts

Telemetry for pin button (pinning/unpinning). Should also work for correctness buttons (saving/unsaving).

feat: telemetry for pin/unpin

---

README.md

Fix capitalization in the README.md FSE'23 citation

fix: update README.md citation

---

package.json
packages/runtime/package.json

chore: update version to 0.1.16

---

package.json
packages/runtime/.gitignore
packages/runtime/package.json

chore: update version to 0.1.18

---

package.json

Update vscode marketplace description to match the description on GitHub.

chore: update vscode marketplace description

---

assets/ui/FuzzPanelMain.css
src/ui/FuzzPanel.ts

Various minor UI tweaks, including:
- Reduced size of array length inputs 
All changes are on the `Validating` tab.
- Clarified text for `+ (new validator function)` tooltip
- Shorten the text of the `heuristic validator` checkbox
- Add explanatory text for `human validator`
- Clarified description on (i) tab under heading `What was returned` in `errors only` mode when all tests passed.
- In `errors only` mode with zero results, a clarifying informational message is now shown below the `Test` button indicating that all tests passed. This resolves #104.

chore: minor ui tweaks

---

package.json
packages/runtime/package.json
src/fuzzer/analysis/typescript/ProgramDef.ts

This PR resolves #72 by providing the importing module path to node's module resolver.

fix: resolve #72 

---

assets/ui/FuzzPanelMain.js

Hide the expected value field and skip value validation when an exception is expected by the human validator.

fix: expected value should be optional when human expects an exception

---

CONTRIBUTING.md
README.md

Also updated `README.md` to point potential contributors to `CONTRIBUTING.md`

chore: add contributor guide

---

assets/ui/FuzzPanelMain.css
assets/ui/FuzzPanelMain.js

This fixes #160 and seems close enough to #152 - PTAL :-)

fix: correct mouse pointer over human & pin buttons (resolves #160)

---

assets/ui/FuzzPanelMain.js
package.json
src/fuzzer/Fuzzer.test.ts
src/fuzzer/Fuzzer.ts
src/fuzzer/Types.ts
src/ui/FuzzPanel.ts

For #166; also relevant to the discussion in #159.

feat: add max dupe inputs to more options

---

src/fuzzer/analysis/typescript/ProgramDef.ts

feat: skip functions that raise errors in _findFunctions

---

README.md

Noticed "unsigne" and just threw the file to ChatGPT which pointed out a few additional things.

chore: fix README.md typos

---

src/ui/FuzzPanel.ts

The JSON test file upgrade should be incremental. Trying to upgrade every old version to the current version is not sustainable, so make upgrades simply between two adjacent versions and loop until the upgrade is complete.

fix: simplify json test file upgrade

---

src/ui/FuzzPanel.ts

This PR automatically saves the file (if unsaved) and adds the necessary import to the top of the file when generating a validator for the first time. While making this change, we also now auto-save the file when the `NaNofuzz...` button is clicked, which eliminates an unnecessary error message for users.
The import generated is: `import { FuzzTestResult } from "@nanofuzz/runtime";`

feat: generate `FuzzTestResult` import when generating validator (#193)

---

src/ui/FuzzPanel.ts

This PR resolves #176 by adding user feedback for some additional cases where invalid TypeScript is detected upon pressing the `Test` and `Add Validator` buttons. In the case of `Test`, we now show an error in `FuzzPanel`'s error message pane (where the results grid usually resides). With `Add Validator`, we now show a VS Code error message. 
Special thanks to @ZiyaoWei for tracking down this problem and originally writing up the details of the issue in #56.

fix: silent compile errors (#176)

---

src/ui/FuzzPanel.ts

This PR addresses #217 by changing focus to the validator upon generating the new validator

fix: adding validator should bring it into focus (#217)

---

.gitignore
assets/ui/FuzzPanelMain.ts
assets/ui/utils.ts
build.js
package.json
src/ui/FuzzPanel.ts
tsconfig.json
yarn.lock

A lot of changes are included here - @cmumatt you can probably review this commit by commit although the last few commits might be somewhat messy, LMK if you prefer I use some sort of tool to split up the PR!
There are still quite a few `any`s left but they mostly seem to be nontrivial to convert, and for them perhaps first refactoring the code and then adding types might be easier.
Fixes #109.

refactor: Convert FuzzPanelMain.js to FuzzPanelMain.ts

---

package.json
packages/runtime/package.json

Update the NaNofuzz version to `0.3.6`

chore: update version to v0.3.6

---

src/fuzzer/Compiler.ts
src/fuzzer/Fuzzer.ts
src/fuzzer/Types.ts
src/fuzzer/analysis/typescript/ProgramDef.ts
src/telemetry/Telemetry.ts
src/ui/FuzzPanel.ts

Clean up some of the typing warnings

chore: improve typing

---

package.json
yarn.lock

Update the `@vscode/vsce ` package and remove the unused `@vscode/test-electron`

chore: update ms packages
