src/examples/1.test.ts
src/examples/1.ts
src/extension.ts
src/fuzzer/Fuzzer.test.ts
src/fuzzer/Fuzzer.ts
src/fuzzer/analysis/Typescript.test.ts
src/fuzzer/analysis/Typescript.ts
src/fuzzer/generators/GeneratorFactory.ts

Add object literal support to fuzzer.  This allows NaNofuzz to analyze and fuzz functions with literal object arguments such as the following function's `wells` argument:
```
export function minValue(  wells: {
valueText?: number;
value?: number;
}[]
): number {
return Math.min(...wells.map((d) => Number(d.valueText) || Number(d.value)));
}
```
This change adds the notion that function arguments may have child arguments such that an object argument may contain `n` sub-arguments, each of which has the same attributes of any other argument.  A new generator function specific to object arguments loops over the object's children and randomizes their inputs in the same manner arguments have previously been randomized.
When the user is queried for range input by the VS Code extension, a similar …

feat: literal object argument support

---

.gitignore
README.md
package.json
src/extension.ts
src/fuzzer/analysis/typescript/ArgDef.ts
src/telemetry/Logger.ts
src/telemetry/Memory.ts
src/telemetry/Telemetry.ts
src/ui/FuzzPanel.ts
tsconfig.json

This PR adds telemetry to the NaNofuzz extension.
This PR integrates the former `pursecode` extension into NaNofuzz.  Telemetry is persisted to a `telemetry` folder in the root of the project, which allows a simple commit of data to the repo fork/branch at the end of the session.
In addition to the normal `pursecode` telemetry, the following FuzzPanel events are also added:
- Opening a FuzzPanel
- Changing visibility or activeness of a FuzzPanel
- Executing the Fuzzer, including results.

feat: Add Telemetry

---

.gitignore
.vscodeignore
package.json
yarn.lock

This PR adds a `yarn package` script which creates a `nanofuzz-0.1.0.vsix` file that can be installed locally in VS Code. This should also allow us to publish to the VS Code marketplace via `npx vsce publish --yarn`, once @maxkrieger finishes giving me permissions to publish under the `penrose` publisher.

build: Package VSIX

---

src/telemetry/Logger.ts

This PR modifies the `Logger`'s `persistChunk` method to write to the workspace, instead of trying to write into the extension source directory.

fix: Externalize telemetry

---

.vscodeignore
assets/ui/FuzzPanelMain.js
package.json
src/fuzzer/Fuzzer.ts
src/fuzzer/adapters/JestAdapter.ts
src/fuzzer/analysis/typescript/ArgDef.ts
src/fuzzer/analysis/typescript/FunctionDef.test.ts
src/telemetry/Logger.ts
src/ui/FuzzPanel.ts

- Properly display Infinity and NaN in test results summary (previously serialized as null)
- Exclude pinned tests from counting against the maximum number of tests specified
- Functions with zero-arguments now bypass the input duplicate check

fix: bug fixes for v0.1.11

---

package.json
yarn.lock

Bump TypeScript version from ^4.1.3 to ^4.9.5. 
This resolves a large number of TypeScript errors and warnings in recent versions of VS Code.

chore: bump TS version

---

README.md

VSC Marketplace apparently has a problem parsing markdown URLs that contain a `#` inside the URL description. This change removes the `#` from the description so that our README.md displays properly on the VSC Marketplace.

fix: vsc marketplace markdown parsing error

---

assets/ui/FuzzPanelMain.js
package.json
src/fuzzer/Fuzzer.test.ts
src/fuzzer/Fuzzer.ts
src/fuzzer/Types.ts
src/ui/FuzzPanel.ts

This PR adds a new "error only" mode to NaNofuzz, which only reports failed tests. Passed tests are not reported.
This mode may be turned on using the `more options` panel, and you may tell the fuzzer to stop after a specific number of failed tests. This mode allows NaNofuzz to approximate the behavior of some other property-based testing tools that may only report a single failing counter-example.

feat: error-only mode

---

assets/ui/FuzzPanelMain.css
src/fuzzer/Fuzzer.ts
src/fuzzer/Types.ts
src/ui/FuzzPanel.ts

This PR adds a new informational tab to the results grid that explains why NaNofuzz stopped testing and provides some basic information about the tests it ran.

feat: explain stop reason

---

tsconfig.json

Eliminates the need to build the `runtime` npm package prior to building the extension.

fix: resolve #111

---

src/fuzzer/Fuzzer.test.ts
src/fuzzer/Fuzzer.ts

This PR:
1. Passes the PUT a copy of its input rather than the fuzzer's record of the input
2. Adds a new test to verify that PUTs cannot modify the fuzzer's input record

fix: add missing copy of PUT input

---

assets/ui/FuzzPanelMain.js
package.json
packages/runtime/package.json
src/fuzzer/Types.ts
src/fuzzer/generators/GeneratorFactory.test.ts
src/fuzzer/generators/GeneratorFactory.ts
src/ui/FuzzPanel.ts

Corrects the issue where input ranges were not restored when reloading the fuzz panel. This change also:
- Adds an UI control on the fuzz panel so the user may set the string generator alphabet
- Adds a new option (`nanofuzz.ui.codeLens.ignoreFilePattern`) that tells NaNofuzz to ignore files that match a regex. This feature is mostly to support running studies.

Fix #139: Input ranges not restored

---

package.json
packages/runtime/package.json
src/fuzzer/Compiler.ts
src/ui/FuzzPanel.ts

Fix #143 by using the fuzzer's default `strCharset` when the one from the UI is an empty string. This is similar to how we treat other UI fields when they are cleared.
Fix #136 by expanding the error message such that it now suggests the user check the file for errors and we also now provide the filename.
Update the NaNofuzz version to `v0.3.4`.

Fix #143 and #136

---

assets/ui/FuzzPanelMain.js
src/fuzzer/Fuzzer.ts
src/fuzzer/Types.ts
src/fuzzer/adapters/JestAdapter.ts
src/ui/FuzzPanel.ts

Output Jest test cases for each pinned test and property validator used by the fuzzer when property validation is enabled. This change also removes the old `validator?` fields as they are unused.

fix: resolve #147

---

package.json
src/ui/FuzzPanel.ts

Added a new configuration option, `nanofuzz.name`, for obscuring NaNofuzz' name in user-facing screens and messages for the purpose of running studies. Limitations of this change include that it does not change the names of the `nano.test` files nor does it modify the `JestAdapter` output.

fix: resolve #154

---

src/fuzzer/Types.ts
src/ui/FuzzPanel.ts

While investigating #168 somehow the extension was having build errors on the main branch - instead of investigating exactly why it started throwing errors I added some extra typing information for the compiler which should be useful anyway.

chore: add extra typing information

---

src/fuzzer/Types.ts
src/ui/FuzzPanel.ts

Fixes #168.
Note this is PR contains the changes in #177 - I was trying to create dependent PRs but forgot it cannot target #177 since it is from a fork and not a branch in the main repository 😅

fix: Change the validator generator output to use `boolean | undefined` as the return type

---

src/ui/FuzzPanel.ts

Fixed #185 by clarifying `maxDupeInputs` meaning on (i) tab:
> NaNofuzz stopped testing because it reached the configured maximum number of sequentially-generated duplicate inputs (maxDupeInputs). This can mean NaNofuzz is having difficulty generating further new inputs: the function's input space might be small or near exhaustion. You can change this setting in More Options.

fix: clarify maxDupeInputs on (i) tab

---

src/fuzzer/Fuzzer.ts
src/ui/FuzzPanel.ts

To avoid the possibility of a `NaN` on `maxDupeInputs`, force fuzz panel reload upon upgrade to v0.3.6. Also categorize `NaN` values as invalid for `maxDupeInputs`, `maxTests`, and `maxFailures`.

fix: avoid panel NaNs on upgrade to v0.3.6

---

src/fuzzer/analysis/typescript/FunctionDef.test.ts
src/fuzzer/analysis/typescript/FunctionDef.ts
src/fuzzer/analysis/typescript/ProgramDef.ts
src/fuzzer/analysis/typescript/Types.ts

Adds returnType to FunctionRef so we can use this information.
Potentially this would also allow the implicit oracle to verify the return type matches the value since TypeScript's type system isn't sound? Gradual typing while fuzzing maybe?
Note this is based on #187 and only the top commit is new ~~and if it is to be merged it should be after #187~~ nvm just realized this is based on the main branch.

feat: add returnType to FunctionRef

---

src/fuzzer/analysis/typescript/ArgDef.test.ts
src/fuzzer/analysis/typescript/ArgDef.ts
src/ui/FuzzPanel.ts

Initial support for #164. Note this is based on #190 and only the top commit is new ~~, and if it is to be merged it should be after #190~~ nvm just realized this is based on the main branch.
This also potentially would rename the validator argument `FuzzTestResult`, by choosing one of `["r", "result", "_r", "_result"]` first, and then fallback to `r_{i}` with i between 1 and 1000, and if there are still conflicts just use `r_conflict` with a possible conflict.
```
import { FuzzTestResult } from "@nanofuzz/runtime";
type T = {
a: number;
};
export function a(
r: number,
result: number[],
_r: T,
_result: {
num: number;
nested?: {
str?: string;
};
},
r_1: number[][],
out: number,
output: number,
_out: number,
_output: number,
out_1?: number,
): number {
return r;
};
export function …
```

feat: expand FuzzTestResult in the validator template

---

src/fuzzer/analysis/typescript/ArgDef.ts
src/fuzzer/analysis/typescript/FunctionDef.ts
src/fuzzer/analysis/typescript/ProgramDef.ts
src/ui/FuzzPanel.ts

Adds type annotations to the `out` variable of the generated validator code in the case where the return type of the function is resolved and supported (e.g., can be represented as an `ArgDef`). In the case where the type cannot be resolved or is not yet supported (e.g., union types), no type annotation is generated.
This PR completes the functionality needed to resolve #164 and builds upon the strategy used in #191 where generation of the type annotation code is delegated to `ArgDef`.  Consequently, as support for further types is expanded in `ArgDef` (e.g., in #63), `FuzzPanel` will be able to generate the corresponding annotations for those further types.

feat: generate type annotation for `out` in validator

---

assets/ui/FuzzPanelMain.js
src/fuzzer/Fuzzer.test.ts
src/fuzzer/Fuzzer.ts
src/fuzzer/Types.ts
src/fuzzer/adapters/JestAdapter.ts
src/fuzzer/analysis/typescript/FunctionDef.test.ts
src/fuzzer/analysis/typescript/FunctionDef.ts
src/fuzzer/analysis/typescript/ProgramDef.ts
src/fuzzer/analysis/typescript/Types.ts
src/ui/FuzzPanel.ts

This PR resolves #73 by turning off the implicit oracle's `undefined` check in the case where the function has a declared return type of `void`. For simplicity, we do not attempt to determine if the function's return type should or should not be `void`; rather, we simply observe the declared return type and act accordingly. #194 is also resolved by this PR.
Feedback regarding the `void`/non-`void` mode of the implicit oracle is conveyed via `FuzzPanel` tooltips. Jest test cases now also respect this mode.

fix: heuristic oracle should expect `undefined` for `void` functions

---

assets/ui/FuzzPanelMain.js
src/fuzzer/Fuzzer.test.ts
src/fuzzer/analysis/typescript/ArgDef.test.ts
src/fuzzer/analysis/typescript/ArgDef.ts
src/fuzzer/analysis/typescript/FunctionDef.test.ts
src/fuzzer/analysis/typescript/ProgramDef.ts
src/fuzzer/analysis/typescript/Types.ts
src/fuzzer/generators/GeneratorFactory.ts
src/ui/FuzzPanel.ts

This PR adds support for basic literal types `string`, `number`, and `boolean` such as in the following example:
```TypeScript
type litn = 3;
type lita = "a";
type litb = true;
export function testLit(n:litn, a:lita, b:litb) {return;}
```
Optionality and dimensions are supported. At this time we do not support `RegEx`, `null`, or `bigint` literals nor `TemplateLiteral`, `UnaryExpression`, `UpdateExpression` expressions.

feat: add support for literal types

---

assets/ui/FuzzPanelMain.css
assets/ui/FuzzPanelMain.js
src/fuzzer/Fuzzer.test.ts
src/fuzzer/Types.ts
src/fuzzer/analysis/typescript/ArgDef.test.ts
src/fuzzer/analysis/typescript/ArgDef.ts
src/fuzzer/analysis/typescript/FunctionDef.test.ts
src/fuzzer/analysis/typescript/ProgramDef.ts
src/fuzzer/analysis/typescript/Types.ts
src/fuzzer/generators/GeneratorFactory.ts
src/ui/FuzzPanel.ts

This PR adds support for OR / Union types for the generator, fuzzer, `FuzzPanel`, `TypeDef`, `ArgDef`, and analysis and fuzzer end-to-end unit tests. Some terrible examples of union types:
```TypeScript
type hellos = "hello" | "bonjour" | "olá" | "ciao" | "hej";
type stringOrNumber = string | number;
type maybeString = string | undefined;
```
Union types are implemented in the back-end in a similar way as object types such that each type option is a child type of the union. The generator for union then randomly selects one of the children to generate similar to how it randomly selects intervals.
The `FuzzPanel` UI allows the user to select which OR types to generate during testing along with the usual type-specific options for the input generation (ranges and so-on).
- The `undefined` …

feat: support union types (#63)

---

src/__mocks__/vscode.ts
src/fuzzer/Compiler.ts
src/fuzzer/Fuzzer.test.ts
src/fuzzer/Fuzzer.ts
src/fuzzer/Types.ts
src/fuzzer/analysis/typescript/Types.ts
src/fuzzer/analysis/typescript/Util.ts
src/fuzzer/generators/GeneratorFactory.test.ts
src/fuzzer/generators/GeneratorFactory.ts
src/telemetry/Telemetry.ts
src/ui/FuzzPanel.ts

Closes #206 by adding the ability to set `isNoInput` for optional object members, similar to how we currently handle union members. This feature is exposed via the checkboxes in `FuzzPanel`.

feat: `isNoInput` support for optional object members

---

src/fuzzer/analysis/typescript/ArgDef.test.ts
src/fuzzer/analysis/typescript/ArgDef.ts
src/fuzzer/analysis/typescript/FunctionDef.test.ts
src/fuzzer/analysis/typescript/ProgramDef.ts
src/fuzzer/analysis/typescript/Types.ts
src/ui/FuzzPanel.ts

This PR resolves #205 by adding a `dims` attribute to the concrete type definition (`TypeRef.type.dims`), which we now populate instead of `TypeRef.dims` when building a new concrete `TypeRef`. 
In the case of building a `TypeRef` with a type reference that must be resolved, then the previous (non-concrete) `TypeRef.dims` is filled with the type reference's dimensions such that the subsequently resolved `TypeRef` will have two `dims`: one for the type reference (`TypeRef.dims`) and one for the concrete type definition (`TypeRef.type.dims`).
`ArgDef.fromTypeRef()` has been modified to sum both `dims` properties when constructing a new `ArgDef` and determining its dimensions. The example from the original issues has been expanded into a test case.

fix: dims of type refs w/arrays (#205)

---

assets/ui/FuzzPanelMain.js
src/fuzzer/Fuzzer.ts
src/fuzzer/Types.ts

This PR adds the validator function name to the exception message displayed in `FuzzPanel`'s results grid. 
- Currently the fuzzer returns 0-1 validator exceptions such that if multiple validators throw exceptions for a particular input example, the fuzzer only tells the user about one of them. This PR does not resolve that limitation, which we likely will want to resolve in the future.

fix: disambiguate validator exception msgs (#163)

---

src/ui/FuzzPanel.ts

Rather than blocking the user when a function's argument was deleted, this PR discards any extra arguments on load and issues an informational message so that the user may continue testing.

fix: fuzzpanel input has x but the function has y (#181)

---

assets/ui/FuzzPanelMain.css
assets/ui/FuzzPanelMain.js
src/ui/FuzzPanel.ts

This PR resolves #107 by adding a hyperlink from the `FuzzPanel` back to the PUT's source code. This hyperlink is in the form of a VS Code text document icon to the right of the function name at the top of the `FuzzPanel`:

feat: link from FuzzPanel to put (#107)

---

src/ui/FuzzPanel.ts

Users should not encounter this situation, but in the interim NaNofuzz releases, it was possible to end up with a `nano.json` file that is missing a `maxDupeInputs` option. Upon upgrade of the `nano.json` file from `v0.3.3` to `v0.3.6`, check for the missing `maxDupeInputs` value and fill the user's default value if it is missing.

fix: fill maxDupeInputs on upgrade from v0.3.3 if missing

---

assets/ui/FuzzPanelMain.ts

This PR implements the fix that we discussed in PR #222 to avoid the exception than can otherwise happen when clicking the pin button. Fixes #224.

fix: pin button can throw exception (#224)

---

src/fuzzer/analysis/typescript/ProgramDef.ts
src/telemetry/Telemetry.ts
src/ui/FuzzPanel.ts

This PR further shortens the list of type warnings that remain in the code base. This change primarily addresses explicit `any`types previously present in exception handlers.

chore: improve typing

---

assets/ui/FuzzPanelMain.css

Narrows the left margin of `fuzzGrid`, `fuzzGridPanel`, and first column of `fuzzGrid`.

fix: narrow fuzzgrid left margin (#232)

---

.gitignore
.vscode/settings.json
CONTRIBUTING.md
flake.lock
flake.nix

This PR makes it easy for developers using [Nix](https://nixos.org/) and [direnv](https://direnv.net/) to build NaNofuzz locally, so now (instead of having to have Node.js and Yarn already installed), they just need to clone it and then create a one-line `.envrc` file telling direnv to use the Nix config:
```sh
gh repo clone nanofuzz/nanofuzz
cd nanofuzz
echo 'use flake' > .envrc
direnv allow
```
I added this `.envrc` file (along with direnv's generated `.direnv` folder) to `.gitignore` because not everyone will want to use direnv with `flake.nix`. Also, I modified `.vscode/settings.json` so VS Code doesn't try to apply Prettier to _every_ file, only the ones it should actually be trying to format.

feat: support development via Nix and direnv

---

src/ui/FuzzPanel.ts

Correct the typo in the upgrade log message.
E.g., `Upgraded test set in file ${jsonFile} to ${inputTests.version} to ${testSet.version}` --> `Upgraded test set in file ${jsonFile} from ${inputTests.version} to ${testSet.version}`

fix: upgrade msg typo

---

package.json
yarn.lock

Update typescript to v5.9.2 (to match vscode) and also tsdoc

chore: bump typescript and tsdoc

---

src/fuzzer/Compiler.ts

Typescript v5.9.2 and many other versions subsequent to v4.9.2 use a shim to load `tsc`. 
When called from `Compiler`, this shim is unable to `require` `tsc`. My guess is that a path in the `script.runInContext()` context is set incorrectly, which prevents the shim's `require` from resolving the relative module path of the real `tsc`.
Calling the actual `tsc` directly also fixes the problem, which is the strategy adopted by this change.

fix: tsc v5.9.2 `tsc` shim require failure

---

.vscode/settings.json

Apply the node arg `--no-experimental-strip-types` to Jasmine Test Explorer so that VS Code's testing pane works with the experimental strip type feature that Node turns on by default now.

fix: jasmine test explorer
